## Server Configuration
#server.port=8080
##server.servlet.context-path=/
#
## SSL Configuration
#server.ssl.key-store=classpath:keystore.p12
#server.ssl.key-store-password=walletwise123
#server.ssl.key-store-type=PKCS12
#server.ssl.key-alias=walletwise
#
## Database Configuration
#spring.datasource.url=${DATASOURCE_URL}
#spring.datasource.username=${DATASOURCE_USER}
#spring.datasource.password=${DATASOURCE_PASSWORD}
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
#frontend.url=${FRONTEND_URL}
#
## JPA / Hibernate
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#spring.jpa.properties.hibernate.format_sql=true
#
## JWT Configuration
#jwt.secret=0255db5f6a42bbfdde6da196d02440fbb67b1ebf48f10170e1768e86
#jwt.expiration=86400000
#
## AWS SES Configuration
#aws.accessKeyId=${AWS_ACCESS_KEY_ID}
#aws.secretKey=${AWS_SECRET_ACCESS_KEY}
#aws.region=ap-south-1
#aws.ses.from-email=salikmulla18@gmail.com
#
## OTP Configuration
#otp.expiration-minutes=5
#otp.length=6
#
## Logging
#logging.level.org.springframework=INFO
#logging.level.com.walletwise=DEBUG



# ================= SERVER =================
server.port=8080

# ================= SSL =================
#server.ssl.key-store=classpath:keystore.p12
#server.ssl.key-store-password=walletwise123
#server.ssl.key-store-type=PKCS12
#server.ssl.key-alias=walletwise

# ================= DATABASE =================
# ? REMOVE custom mapping
# Spring Boot will AUTO pick SPRING_DATASOURCE_* from ENV

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ================= FRONTEND =================
frontend.url=${FRONTEND_URL}

# ================= JPA =================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ================= JWT =================
jwt.secret=0255db5f6a42bbfdde6da196d02440fbb67b1ebf48f10170e1768e86
jwt.expiration=86400000

# ================= AWS =================
aws.accessKeyId=${AWS_ACCESS_KEY_ID}
aws.secretKey=${AWS_SECRET_ACCESS_KEY}
aws.region=ap-south-1
aws.ses.from-email=salikmulla18@gmail.com

# ================= GMAIL SMTP =================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ================= OTP =================
otp.expiration-minutes=5
otp.length=6

# ================= LOGGING =================
logging.level.org.springframework=INFO
logging.level.com.walletwise=DEBUG